version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - REDIS_URL=redis://redis:6379
